//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
//
namespace ASAPClient
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.Web.Services.Description;
	using System.ComponentModel;
	using System.Web.Services;
	using ASAPTypes;


	/// <remarks/>
	[DebuggerStepThroughAttribute()]
	[DesignerCategoryAttribute("code")]
	[WebServiceBindingAttribute(Name="AsapInstanceBinding", Namespace="http://www.oasis-open.org/asap/0.9/asap.wsdl")]
	[XmlIncludeAttribute(typeof(instancePropertiesType))]
	[XmlIncludeAttribute(typeof(string[]))]
	public class AsapInstanceBinding : SoapHttpClientProtocol
	{

		public Request RequestValue;

		public Response ResponseValue;

		/// <remarks/>
		public AsapInstanceBinding()
		{
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/instance/GetProperties", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("GetPropertiesRs", typeof(instancePropertiesType), Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public instancePropertiesType GetProperties([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] GetPropertiesRq GetPropertiesRq)
		{
			object[] results = this.Invoke("GetProperties", new object[] {
																			 GetPropertiesRq});
			return ((instancePropertiesType)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginGetProperties(GetPropertiesRq GetPropertiesRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetProperties", new object[] {
																	  GetPropertiesRq}, callback, asyncState);
		}

		/// <remarks/>
		public instancePropertiesType EndGetProperties(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((instancePropertiesType)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/instance/SetProperties", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("SetPropertiesRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public SetPropertiesRs SetProperties([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] SetPropertiesRq SetPropertiesRq)
		{
			object[] results = this.Invoke("SetProperties", new object[] {
																			 SetPropertiesRq});
			return ((SetPropertiesRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginSetProperties(SetPropertiesRq SetPropertiesRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("SetProperties", new object[] {
																	  SetPropertiesRq}, callback, asyncState);
		}

		/// <remarks/>
		public SetPropertiesRs EndSetProperties(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((SetPropertiesRs)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/instance/Subscribe", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("SubscribeRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public SubscribeRs Subscribe([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] SubscribeRq SubscribeRq)
		{
			object[] results = this.Invoke("Subscribe", new object[] {
																		 SubscribeRq});
			return ((SubscribeRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginSubscribe(SubscribeRq SubscribeRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Subscribe", new object[] {
																  SubscribeRq}, callback, asyncState);
		}

		/// <remarks/>
		public SubscribeRs EndSubscribe(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((SubscribeRs)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/instance/Unsubscribe", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("UnsubscribeRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public UnsubscribeRs Unsubscribe([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] UnsubscribeRq UnsubscribeRq)
		{
			object[] results = this.Invoke("Unsubscribe", new object[] {
																		   UnsubscribeRq});
			return ((UnsubscribeRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginUnsubscribe(UnsubscribeRq UnsubscribeRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Unsubscribe", new object[] {
																	UnsubscribeRq}, callback, asyncState);
		}

		/// <remarks/>
		public UnsubscribeRs EndUnsubscribe(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((UnsubscribeRs)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/instance/ChangeState", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("ChangeStateRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public ChangeStateRs ChangeState([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] ChangeStateRq ChangeStateRq)
		{
			object[] results = this.Invoke("ChangeState", new object[] {
																		   ChangeStateRq});
			return ((ChangeStateRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginChangeState(ChangeStateRq ChangeStateRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("ChangeState", new object[] {
																	ChangeStateRq}, callback, asyncState);
		}

		/// <remarks/>
		public ChangeStateRs EndChangeState(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((ChangeStateRs)(results[0]));
		}
	}

	/// <remarks/>
	[DebuggerStepThroughAttribute()]
	[DesignerCategoryAttribute("code")]
	[WebServiceBindingAttribute(Name="AsapFactoryBinding", Namespace="http://www.oasis-open.org/asap/0.9/asap.wsdl")]
	[XmlIncludeAttribute(typeof(factoryPropertiesType))]
	[XmlIncludeAttribute(typeof(string[]))]
	public class AsapFactoryBinding : SoapHttpClientProtocol
	{

		public Request RequestValue;

		public Response ResponseValue;

		/// <remarks/>
		public AsapFactoryBinding()
		{
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/factory/GetProperties", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("GetPropertiesRs", typeof(factoryPropertiesType), Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public factoryPropertiesType GetProperties([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] GetPropertiesRq GetPropertiesRq)
		{
			object[] results = this.Invoke("GetProperties", new object[] {
																			 GetPropertiesRq});
			return ((factoryPropertiesType)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginGetProperties(GetPropertiesRq GetPropertiesRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetProperties", new object[] {
																	  GetPropertiesRq}, callback, asyncState);
		}

		/// <remarks/>
		public factoryPropertiesType EndGetProperties(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((factoryPropertiesType)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/factory/CreateInstance", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("CreateInstanceRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public CreateInstanceRs CreateInstance([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] CreateInstanceRq CreateInstanceRq)
		{
			object[] results = this.Invoke("CreateInstance", new object[] {
																			  CreateInstanceRq});
			return ((CreateInstanceRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginCreateInstance(CreateInstanceRq CreateInstanceRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("CreateInstance", new object[] {
																	   CreateInstanceRq}, callback, asyncState);
		}

		/// <remarks/>
		public CreateInstanceRs EndCreateInstance(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((CreateInstanceRs)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/factory/ListInstances", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlArrayAttribute("ListInstancesRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		[return: XmlArrayItemAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd", IsNullable=false)]
		public Instance[] ListInstances([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] ListInstancesRq ListInstancesRq)
		{
			object[] results = this.Invoke("ListInstances", new object[] {
																			 ListInstancesRq});
			return ((Instance[])(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginListInstances(ListInstancesRq ListInstancesRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("ListInstances", new object[] {
																	  ListInstancesRq}, callback, asyncState);
		}

		/// <remarks/>
		public Instance[] EndListInstances(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Instance[])(results[0]));
		}
	}

	/// <remarks/>
	[DebuggerStepThroughAttribute()]
	[DesignerCategoryAttribute("code")]
	[WebServiceBindingAttribute(Name="AsapObserverBinding", Namespace="http://www.oasis-open.org/asap/0.9/asap.wsdl")]
	[XmlIncludeAttribute(typeof(observerPropertiesType))]
	[XmlIncludeAttribute(typeof(string[]))]
	public class AsapObserverBinding : SoapHttpClientProtocol
	{

		public Request RequestValue;

		public Response ResponseValue;

		/// <remarks/>
		public AsapObserverBinding()
		{
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/observer/GetProperties", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("GetPropertiesRs", typeof(observerPropertiesType), Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public observerPropertiesType GetProperties([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] GetPropertiesRq GetPropertiesRq)
		{
			object[] results = this.Invoke("GetProperties", new object[] {
																			 GetPropertiesRq});
			return ((observerPropertiesType)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginGetProperties(GetPropertiesRq GetPropertiesRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetProperties", new object[] {
																	  GetPropertiesRq}, callback, asyncState);
		}

		/// <remarks/>
		public observerPropertiesType EndGetProperties(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((observerPropertiesType)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/observer/Completed", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("CompletedRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public CompletedRs Completed([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] CompletedRq CompletedRq)
		{
			object[] results = this.Invoke("Completed", new object[] {
																		 CompletedRq});
			return ((CompletedRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginCompleted(CompletedRq CompletedRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Completed", new object[] {
																  CompletedRq}, callback, asyncState);
		}

		/// <remarks/>
		public CompletedRs EndCompleted(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((CompletedRs)(results[0]));
		}

		/// <remarks/>
		[SoapHeaderAttribute("RequestValue")]
		[SoapHeaderAttribute("ResponseValue", Direction=SoapHeaderDirection.Out)]
		[SoapDocumentMethodAttribute("http://www.oasis-open.org/asap/0.9/asap/observer/StateChanged", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
		[return: XmlElementAttribute("StateChangedRs", Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")]
		public StateChangedRs StateChanged([XmlElementAttribute(Namespace="http://www.oasis-open.org/asap/0.9/asap.xsd")] StateChangedRq StateChangedRq)
		{
			object[] results = this.Invoke("StateChanged", new object[] {
																			StateChangedRq});
			return ((StateChangedRs)(results[0]));
		}

		/// <remarks/>
		public IAsyncResult BeginStateChanged(StateChangedRq StateChangedRq, AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("StateChanged", new object[] {
																	 StateChangedRq}, callback, asyncState);
		}

		/// <remarks/>
		public StateChangedRs EndStateChanged(IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((StateChangedRs)(results[0]));
		}
	}
}
