<%@ Page language="c#" Codebehind="list.aspx.cs" AutoEventWireup="false" Inherits="ASAPClient.list" enableViewState="False"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" >
<HTML>
	<HEAD>
		<title>ASAP Demo - Instance List</title>
		<meta name="GENERATOR" Content="Microsoft Visual Studio .NET 7.1">
		<meta name="CODE_LANGUAGE" Content="C#">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
		<style>.RowHead { FONT-WEIGHT: bold; FONT-FAMILY: Arial; TEXT-ALIGN: left }
	.RowTail { FONT-FAMILY: Arial }
	BODY { FONT-FAMILY: Arial; BACKGROUND-COLOR: #c0c0c0 }
	.Header { FONT-WEIGHT: bold; FONT-SIZE: large; FONT-FAMILY: Arial; HEIGHT: 40px }
		</style>
	</HEAD>
	<body>
		<form id="Form1" method="post" runat="server">
			<asp:Label id="Title" runat="server" CssClass="Header">All Instances</asp:Label>
			<asp:Table id="Table1" runat="server" CellSpacing="0" CellPadding="4" BorderWidth="0px" EnableViewState="False">
				<asp:TableRow BackColor="Teal">
					<asp:TableCell BackColor="Silver" Width="30px"></asp:TableCell>
					<asp:TableCell Text="Name&amp;nbsp;&amp;nbsp;" CssClass="RowHead"></asp:TableCell>
					<asp:TableCell Text="Subject&amp;nbsp;&amp;nbsp;" CssClass="RowHead"></asp:TableCell>
					<asp:TableCell Wrap="False" Text="Instance Key&amp;nbsp;&amp;nbsp;" CssClass="RowHead"></asp:TableCell>
					<asp:TableCell></asp:TableCell>
				</asp:TableRow>
			</asp:Table>
			<TABLE id="Table3" cellSpacing="30" cellPadding="1" border="0">
				<TR>
					<TD align="center" width="60"></TD>
					<TD align="center">
						<asp:Button id="RefreshButton" runat="server" Text="Refresh"></asp:Button></TD>
					<TD align="center">
						<asp:Button id="BackButtn" runat="server" Text="Back"></asp:Button></TD>
				</TR>
			</TABLE>
			The above list was generated by the server.
		</form>
	</body>
</HTML>
